---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: project

outputs:
- name: artifact

run:
  path: project/ci/scripts/build.sh
