resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse.git


jobs:
- name: build
  public: true
  plan:
  - get: project
  - task: build-project
    file: project/renht/ci/tasks/build.yml
- name: deploy
  public: true
  plan:
  - get: project
  - task: deploy-project
    file: project/renht/ci/tasks/deploy.yml
    params:
        PASSWORD: {{password}}
        HOST: {{host}}
        PORT: {{port}}
        PK: {{pk}}
