resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse.git


jobs:
- name: deploy-project
  plan:
  - get: project
    trigger: true
  - task: test
    file: project/ci/tasks/test.yml
  - task: build
    file: project/ci/tasks/build.yml
  - task: deploy
    file: project/ci/tasks/deploy.yml
  - task: smoke-test
    file: project/ci/tasks/smoke_test.yml
  - task: release
    params:
        PASSWORD: {{password}}
        HOST: {{host}}
        PORT: {{port}}
        PK: {{pk}}
