resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse.git
- name: build-artifact
  type: docker-image
  source:
    repository: injectyy/counter
    tag: latest
    username: injectyy
    password: {{password}}


jobs:
- name: deploy-project
  plan:
  - get: project
    trigger: true
  - put: build-artifact
    params:
      build: project
  - task: deploy
    file: project/ci/tasks/deploy.yml
    params:
        PK: {{pk}}
        HOST: {{host}}
        PORT: {{port}}
  - task: smoke-test
    file: project/ci/tasks/smoke_test.yml
