resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse.git


jobs:
- name: deploy_project
  public: true
  plan:
  - get: project
    trigger: true
  - task: test-project
    file: project/ci/tasks/test.yml
  - task: build-project
    file: project/ci/tasks/build.yml
  - task: deploy-project
    file: project/ci/tasks/deploy.yml
    params:
        PASSWORD: {{password}}
        HOST: {{host}}
        PORT: {{port}}
        PK: {{pk}}
